services:
  web-server-1:
    container_name: web-1
    build:
      context: ./web-server
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: "always"

  web-server-2:
    container_name: web-2
    build:
      context: ./web-server
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3001:3000"
    restart: "always"
  forward-proxy:
    container_name: forward-proxy
    build:
      context: ./forward-proxy
      dockerfile: Dockerfile
    environment: 
      - BASE_URL=http://localhost:5000
      - TARGET=http://web-1:3000/, http://web-2:3000/
      - ENV=docker
    expose:
      - "5000"
    ports:
      - "5000:5000"
    restart: "always"