services:
  backend-1:
    container_name: backend-1
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: "always"
  web-server:
    container_name: web-1
    build:
      context: ./web-server
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: "always"
  
  # forward-proxy:
  #   container_name: forward-proxy
  #   depends_on:
  #     - web-server
  #   build:
  #     context: ./forward-proxy
  #     dockerfile: Dockerfile
  #   environment: 
  #     - BASE_URL=http://localhost:5000
  #     - TARGET=http://web-1:3000/
  #     - ENV=docker
  #   expose:
  #     - "5000"
  #   ports:
  #     - "5000:5000"
  #   restart: "always"