FROM bitnami/postgresql

ARG $POSTGRES_DB
ARG $POSTGRES_USER
ARG $POSTGRES_PASSWORD
ARG $POSTGRESQL_PGAUDIT_LOG

ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRESQL_REPLICATION_MODE="master"
ENV POSTGRESQL_REPLICATION_USER="repl_user"
ENV POSTGRESQL_REPLICATION_PASSWORD="repl_user"
ENV POSTGRESQL_PGAUDIT_LOG=$POSTGRESQL_PGAUDIT_LOG
ENV POSTGRESQL_LOG_HOSTNAME=true
ENV ALLOW_EMPTY_PASSWORD=yes

COPY init.sql /docker-entrypoint-initdb.d/